// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickMeWhatToListen.Infrastructure;

#nullable disable

namespace PickMeWhatToListen.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802190424_FixMetadataSyncStatusDefault")]
    partial class FixMetadataSyncStatusDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PickMeWhatToListen.Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPicked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataSyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<long?>("MetadataSyncedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusicBrainzArtistMbid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PickedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WikidataUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsPicked");

                    b.HasIndex("MusicBrainzArtistMbid")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("PickMeWhatToListen.Domain.ArtistMetadataTerm", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetadataTermId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<int>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtistId", "MetadataTermId", "Kind");

                    b.HasIndex("MetadataTermId");

                    b.ToTable("ArtistMetadataTerms");
                });

            modelBuilder.Entity("PickMeWhatToListen.Domain.MetadataTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MetadataTerms");
                });

            modelBuilder.Entity("PickMeWhatToListen.Domain.ReleaseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverArtStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverArtUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverReleaseMbid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstReleaseDate")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzReleaseGroupMbid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId", "FirstReleaseDate");

                    b.HasIndex("ArtistId", "MusicBrainzReleaseGroupMbid")
                        .IsUnique();

                    b.ToTable("ReleaseGroups");
                });

            modelBuilder.Entity("PickMeWhatToListen.Domain.ArtistMetadataTerm", b =>
                {
                    b.HasOne("PickMeWhatToListen.Domain.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PickMeWhatToListen.Domain.MetadataTerm", "MetadataTerm")
                        .WithMany()
                        .HasForeignKey("MetadataTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetadataTerm");
                });

            modelBuilder.Entity("PickMeWhatToListen.Domain.ReleaseGroup", b =>
                {
                    b.HasOne("PickMeWhatToListen.Domain.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
